name: tutorial1

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "hello, this is job1"

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: step2
        run: echo "hello, this is job2"

  job3:
    name: job3
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "hello, this is job3"
  
  job4:
    name: job4
    runs-on: ubuntu-latest
    Needs: [job1, job2]
    steps:
      - name: step4
        run: echo "I am job 4, I am dependent on job1 and job2"