name: tutorial1

on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: set up python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: python version
        run: |
          python -V
          python3 -V
